### ISSUE TITLE
Context Deadline exceeded in helmchart 0.15.0

### ISSUE THREAD

**Issue by 3deep5me** [openbao/openbao-csi-provider#36]
Hi, i get following error after upgrading to the new version via the helm chart:
```
grpc.method=/v1alpha1.CSIDriverProvider/Mount grpc.time=1m0.071520973s grpc.code=Unknown err="error making mount request: couldn't read secret \"db-password\": failed to login: context deadline exceeded"
```
With the old version i do not have this issue, any ideas?

values for the csi integration
```
          injector:
            enabled: false
          server:
            enabled: false
          csi:
            enabled: true
```
values for the bao instance 
```
          injector:
            enabled: false
          server:
            statefulSet:
              securityContext:
                container:
                  seccompProfile:
                    type: RuntimeDefault
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                  runAsNonRoot: true
``` 

I use the jwtauth method in Kubernetes
