### ISSUE TITLE
Coordinate with kubernetes-sigs/secrets-store-csi-driver to support openbao as an accepted provider

### ISSUE THREAD

**Issue by jessebot** [openbao/openbao-csi-provider#5]
We need to submit a PR to https://github.com/kubernetes-sigs/secrets-store-csi-driver to add openbao as a valid provider, as right now, our `SecretProviderClass` resources all have to use `provider: vault` because otherwise, they all fail, as only a few providers are recognized and tested:

- https://github.com/kubernetes-sigs/secrets-store-csi-driver?tab=readme-ov-file#test-status
- https://secrets-store-csi-driver.sigs.k8s.io/getting-started/usage#create-your-own-secretproviderclass-object

Per their docs:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-provider
spec:
  provider: vault        # accepted provider options: akeyless or azure or vault or gcp
  parameters:            # provider-specific parameters

```

_Originally posted by @jessebot in https://github.com/openbao/openbao-csi-provider/issues/4#issuecomment-2143477327_
